example.property: I AM THE DEFAULT CHANGE
spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.datasource.url: jdbc:mysql://127.0.0.1:3306/DIny
spring.datasource.username: dylan
spring.datasource.password: 1slikeFSK
spring.datasource.testWhileIdle: true
spring.datasource.validationQuery: SELECT 1
spring.jpa.database: MYSQL
spring.jpa.show-sql: true