example.property: I AM THE DEV
#com.mysql.jdbc.Driver已经不过期不适合使用了
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.datasource.url: jdbc:mysql://127.0.0.1:3306/DIny
spring.datasource.username: dylan
spring.datasource.password: "{cipher}6b832b8dbda83acc0ab5e69d773c7abf22395daf0b6c933fd92f4c00b99125d4"
spring.datasource.testWhileIdle: true
spring.datasource.validationQuery: SELECT 1
spring.jpa.database: MYSQL
spring.jpa.show-sql: true