server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file://Users/kangweiding/JavaProjects/SpringMicroservice/confsvr/src/main/resources/licensingservice/licensingservice