server:
  port: 8888 #设置监听的端口号
spring:
  profiles:
    active: native #用于存储配置的后端存储库(文件系统)
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kangweiding123/SpringCloud/config
#        native:
#        #配置文件存储的路径
#          searchLocations: /Users/kangweiding/JavaProjects/SpringMicroservice/confsvr/src/main/resources/config/licensingservice/